name: download-apk

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK
        run: |
          curl -L -o Hidezen_VPN.apk https://hidezen.com/download/Hidezen_VPN.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hidezen-apk
          path: Hidezen_VPN.apk
